version: "3.9"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3305:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asd4263
      - MYSQL_DATABASE=smo-dev
      - MYSQL_USER=smodb
      - MYSQL_PASSWORD=asd4263
