import "~/styles/globals.css";

import { Noto_Sans_Thai } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { AppWrapper } from "~/context";

const inter = Noto_Sans_Thai({
  subsets: ["thai"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <AppWrapper>{children}</AppWrapper>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
